import numpy as np
x = np.array([1, 2, 3, 4])
x

In [7]:
y = x
y

array([1, 2, 3, 4])

In [8]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a = np.array([1, 2, 3, 5])
b = np.linspace(0, 2, 4)
c = a - b
c

array([1.        , 1.33333333, 1.66666667, 3.        ])

In [10]:
a ** 2

array([ 1,  4,  9, 25])

这里`np.linspace(0, 2, 4)`表示的是0-2之间4个等分点

In [15]:
a = np.linspace(- np.pi, np.pi, 100)
b = np.sin(a)
c = np.cos(a)

In [20]:
from numpy.random import rand
from numpy.linalg import solve, inv
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])  # 这里得注意小括号中还有个中括号
b = np.array([3, 2, 1])
solve(a,b)


array([-4.83050847,  2.13559322,  1.18644068])

In [21]:
c = rand(3, 3)
np.dot(a, c)

array([[3.32708215, 3.24888155, 2.85967471],
       [7.71923192, 7.85918628, 6.82410748],
       [9.32614962, 9.97305165, 7.91596426]])

#### 关于array

In [35]:
a = np.array([1, 2])
b = np.array([3, 4])
print(b)
print(a * b)
print(np.dot(a, b))

b = np.transpose(b)
print(b)
print(np.dot(a, b))


[3 4]
[3 8]
11
[3 4]
11


这说明对于`array`类型，`*`表示二者的点乘，也就是对应元素相乘，而`dot`则是二者的内积，怎么感觉并没有行列向量的区分啊

In [44]:
A = np.array([[1, 2, 3], [2, 3, 4]])
A[:,1]

array([2, 3])

可以看到，numpy与matlab不同的地方，`A[：，1]`是矩阵`A`的第二列，而不是第一列

In [46]:
from numpy import *
import scipy.linalg

In [62]:
B = np.matrix("[1,2;3,4]")

print('size(B):',size(B))
print('shape(B):',shape(B))

print('size(A):',size(A))
print('shape(A):',shape(A))

size(B): 4
shape(B): (2, 2)
size(A): 6
shape(A): (2, 3)


`size`得到矩阵有几个元素，`shape`得到矩阵的行数和列数。

In [63]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('C[0:2, :]:',C[0:2, :])

C[0:2, :]: [[1 2 3]
 [4 5 6]]


这里也需要注意，`C`的前两行是`C[0:2, :]`，而不是`C[0:1, :]`，也不是`C[1:2, :]`!

分块矩阵合并成一个矩阵,`vstack`是竖直方向上合并矩阵块，`hstack`是水平方向上合并矩阵块。

In [64]:
D = vstack([A,C])
E = hstack([A,B])
print('D:',D)
print('E',E)

D: [[1 2 3]
 [2 3 4]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
E [[1 2 3 1 2]
 [2 3 4 3 4]]


In [72]:
a = array([1, 2, 3, 4, 5, 6])
print(a)
print(a[0:5:2])
print(a[0],a[5])
print(a[1:5])

[1 2 3 4 5 6]
[1 3 5]
1 6
[2 3 4 5]


numpy这里真是奇怪，向量的第n个元素表示为`a[n-1]`,第2到5元素表示为`a[1:5]`。也就是说，`[a:b:c]`表示从`a-1`开始，到`b`结束，`[a-1,a-1+c,...,b]`

python中的for循环，`for ** in ***:`中`**`是`***`中的值，并循环至`***`结束，与`while`语句不同，并没有条件判断。

In [79]:
mylist = [1, 2, 7, 4, 22]
for i in mylist:
    print('i = %d is in my list!' % i)
    

i = 1 is in my list!
i = 2 is in my list!
i = 7 is in my list!
i = 4 is in my list!
i = 22 is in my list!


介绍一个`range`函数.`range(start,stop,step)`得到从`start`开始，到`stop-1`结束内步长为`step`的整数，也就是说不包含`stop`，注意`start`和`stop`都得是整数，而且`start`得比`stop`大。与matlab不同的是步长通常放在范围后面

In [89]:
for i in range(10, 23, 2):
    print('i = %d is in my list!' % i)


i = 10 is in my list!
i = 12 is in my list!
i = 14 is in my list!
i = 16 is in my list!
i = 18 is in my list!
i = 20 is in my list!
i = 22 is in my list!


python中的循环语句`while`，注意要加上冒号`:`

In [80]:
condition = 0
while condition < 10 :
    print(condition)
    condition = condition + 1
print('end')

0
1
2
3
4
5
6
7
8
9
end


In [74]:
print(range(5))
print(tuple(range(5)))

range(0, 5)
(0, 1, 2, 3, 4)


In [80]:
sum = 0
for x in list(range(101)):
    sum = sum + x
print(sum)

sum = 0
for x in range(101):
    sum = sum + x
print(sum)

a = range(101)
print(a)
print(a[0])

5050
5050
range(0, 101)
0


那么现在`a = range(100)`是什么数据格式？

In [81]:
sum = 0
x = 0
while(x <= 100):
    sum = sum + x
    x = x + 1
print(sum)

5050


#### break
在循环中，`break`语句可以提前退出循环。

In [85]:
n = 1
while(n < 100):
    if n > 10:
        break
    print(n)
    n = n + 1
print('end')

1
2
3
4
5
6
7
8
9
10
end


#### continue
在循环过程中，通过`continue`语句，跳过当前的这次循环，直接开始下一次循环

In [1]:
n = 0
while n < 10:
    n = n + 1
    if n % 2 == 0:
        continue
    print(n)
print('end')

1
3
5
7
9
end


### if 判断
```
    if condition:
        expressions
```

In [90]:
i = 1
if i == 1:
    print('yes')
    

yes


`if else`判断
```
    if condition:
        ture expressions
    else:
        false expressions
```

In [91]:
if i ==2:
    print('yes')
else:
    print('no')
        

no


`if-else`行内表达式实现三目操作符`condition ? value1 : value2`

In [96]:
worked1 = True
result = 'done' if worked1 else 'not yet'
print(result)

worked2 = False
result = 'done' if worked2 else 'not yet'
print(result)

done
not yet


这里有一点需要注意：是`True`而不是`true`

`if elif else`：实现多个条件判断

In [98]:
i = 2
if i == 1:
    print('i = 1')
elif i ==2:
    print('i = 2')
else:
    print('i dont know')


i = 2


`if`语句执行时从上往下判断，如果在某个判断上是`True`，把判断对应的语句执行后，会忽略掉剩下的`elif`和`else`。

In [69]:
# 练习
hight = 1.75
weight = 80.5
bmi = weight / (hight ** 2)
if bmi > 32:
    print('严重肥胖！')
elif bmi > 28:
    print('肥胖！')
elif bmi > 25:
    print('过重！')
elif bmi > 18.5:
    print('正常！')
else:
    print('过轻！')


过重！


还是需要进一步了解`dict`

局部变量与全局变量：在`def`中可以定义一个局部变量，只在该`fun`中有效。全局变量在局部中使用需要在`fun()`中声明

In [3]:
a = 50
def testfunction5(b):
    global a
    result = b - a
    print(result)
testfunction5(10)

-40


**Python模块安装**

外部模块：
需要在python脚本中`import`的模块
```
import numpy as np
import matplotlib as plt
```
这里的Numpy和matplotlib都是外部模块，需要**安装**后才会有，不属于Python自带的模块


#### 读写文件
`\n`换行命令

In [4]:
text ='This is my first test. This is the second line. This is the third'
print(text) #没有换行命令
print('\n')
text ='This is my first test.\n This is the second line.\n This is the third'
print(text)
print('\n')
text ='This is my first test.\nThis is the second line.\nThis is the third'
print(text)

This is my first test. This is the second line. This is the third


This is my first test.
 This is the second line.
 This is the third


This is my first test.
This is the second line.
This is the third


`open`读文件方式： 
使用`open`能够打开一个文件，`open`的第一个参数为文件名和路径，第二个参数为将要以什么方式打开，如`w`为可写方式，如果计算机没有找到该文件，则创建一个新文件，并命名为参数中的文件名


In [7]:
my_file = open('mytest.txt', 'w')
my_file.write(text)  # 该语句会写入先前定义好的字符串 text
my_file.close()

这里要注意，用`'w'`方式打开的文件，写入内容时是覆盖式写入。

`\t` tab对齐：使用`\t`能够达到`tab`对齐的效果

In [10]:
text ='\tThis is my first test.\n\tThis is the second line.\n\tThis is the third'
print(text)

	This is my first test.
	This is the second line.
	This is the third


给文件增加内容，通过`'a'`的方式打开文件

In [11]:
text = '\nThis is appended file'
myfile = open('mytest.txt','a')
myfile.write(text)
myfile.close()

读取文件内容`.read()`，使用`file.read()`能够读取到文本的所有内容。(这里和`.write()`类似)

In [15]:
myfile = open('mytest.txt','r')
content = myfile.read()
print(content)
myfile.close()

This is my first test.
This is the second line.
This is the third
This is appended file


按行读取 `.readline()`：在文本中一行行的读取文本，读取的内容与使用的次数有关。

In [16]:
myfile = open('mytest.txt','r')
content = myfile.readline()
print('第一行：',content)

第一行： This is my first test.



In [18]:
content = myfile.readline()
print('第二行：',content)
myfile.close()

第二行： This is the third



读取所有行`file.readlines()`：读取所有行，将每一行的结果存储在`list`中，并可以使用像for一样的迭代器迭代这些行结果。

In [22]:
myfile = open('mytest.txt','r')
content = myfile.readlines()
print(content)
print('\n')
for item in content:
    print(item)


['This is my first test.\n', 'This is the second line.\n', 'This is the third\n', 'This is appended file']


This is my first test.

This is the second line.

This is the third

This is appended file


可以看到，得到的`content`并不是字符串

##### 格式化
用`%`输出格式化的字符串，在字符串内部，`%s`表示用字符串替换，`%d`表示用整数替换，常见的还包括`%f`为浮点数，`%x`为十六进制数。**注意：有几个占位符，后面就得跟几个变量或者值，顺序要对应好**

In [34]:
a = '\'This is a string\''
b = 0xa1
c = 10
d = 3.14159265358979
print('这是一个关于占位符的测试：\n%s\n%x\n%d\n%f' % (a,b,c,d))  #注意没有逗号

这是一个关于占位符的测试：
'This is a string'
a1
10
3.141593


此外，格式化整数和浮点数还可以指定是否补0和整数与小数的位数

In [41]:
print('%03d\n' % c)
print('%.2f\n' %d)

010

3.14



list和tuple：`list`列表是Python内置的一种数据类型。`list`是一种有序的集合，可以随时添加和删除其中的元素。

In [43]:
classmate = ['Mike', 'Jone', 'Snow']
classmate
for item in classmate:
    print(item)


Mike
Jone
Snow


变量`classmate`就是一个`list`，用`len()`可以获得`list`元素的个数

In [44]:
num = len(classmate)
print(num)

3


用索引来访问`list`中每个位置的值：

In [45]:
print(classmate[0])
print(classmate[1])
print(classmate[2])

Mike
Jone
Snow


索引最后一个元素可以用`[len(classmate)-1]`，也可以用直接用`[-1]`，同理倒数第二个为`[-2]`

In [47]:
print(classmate[num - 1])
print(classmate[-1])
print(classmate[-2])
print(classmate[-3])

Snow
Snow
Jone
Mike


`list`追加元素到末尾:`append`，也可以把元素插到指定的位置`insert`。

In [49]:
classmate.append('UZI')
print(classmate)
classmate.insert(1,'Jack')
print(classmate)

['Mike', 'Jone', 'Snow', 'UZI', 'UZI']
['Mike', 'Jack', 'Jone', 'Snow', 'UZI', 'UZI']


删除`list`末尾的元素：`pop`，以及删除指定位置的元素

In [50]:
classmate.pop()
print(classmate)
classmate.pop(1)

['Mike', 'Jack', 'Jone', 'Snow', 'UZI']


'Jack'

将某个元素替换成别的元素，可以直接赋值给对应的索引位置。

In [52]:
classmate[0] = 'JR.Mike'  #这里是对第一个赋值
print(classmate)

['JR.Mike', 'Jone', 'Snow', 'UZI']


`list`中元素的数据类型也可以不同

In [53]:
L = ['Apple', 1, True]
print(L)

['Apple', 1, True]


`list`中的元素也可以是另一个list（那这个`list`有自己的变量名吗）

In [54]:
La = ['banana', 2, False]
L.append(La)
print(L)

['Apple', 1, True, ['banana', 2, False]]


`tuple`，另一种有序列表叫做元组：`tuple`。`tuple`与`list`类似，**但是一旦初始化后就不能修改**，可以看到是用括号`()`表示的

In [55]:
classmates = ('JR.Mike', 'Jack', 'Jone')
print(classmates)

('JR.Mike', 'Jack', 'Jone')


**注意**：定义只有一个元素的tuple时，要在元素后面加上一个逗号。python也是这样显示的

In [56]:
t = (1,)
print(t)

(1,)


用索引访问`tuple`中的元素

In [58]:
print(classmates[1])
print(t[0])

Jack
1


‘可变的’的`tuple`，也就是`tuple`中的元素为`list`（那么`list`中的元素可以是`tuple`吗？）

In [60]:
t1 = ('Jack', [50, 60])
print(t1)
t1[1][1] = 70
print(t1)

l1 = ('Jone', (50, 60))
print(l1)

('Jack', [50, 60])
('Jack', [50, 70])
('Jone', (50, 60))


`list`得到二维数组

In [63]:
m1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(m1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [68]:
L = [
    ['Apple', 'Google', 'Microsoft'],
    ['Java', 'Python', 'Ruby', 'PHP'],
    ['Adam', 'Bart', 'Lisa']
]

print(L[0][0],L[1][1],L[2][2],sep = '\n')   

Apple
Python
Lisa


这里的`sep = '\n'`表示以换行作为分隔（应该是这个意思吧！）

In [83]:
#练习
L = ['Bart', 'Lisa', 'Adam']
for name in L:
    print('Hello, %s!' %(name))


Hello, Bart!
Hello, Lisa!
Hello, Adam!


### 使用dict和set
#### dict：
python内置了字典：`dict`的支持，使用key-value存储，具有**极快的查找速度**  
将数据放入`dict`除了初始化时指定外，还可以通过key放入  
由于一个key只能对应一个value，所以多次对一个key放入value，后面的值会冲掉前面的值  
key可以是整数，也可以是字符串，但是不能为list
dict内部存放的顺序与key放入的顺序无关

In [9]:
d = {'Mike':94, 'Bob':75, 'Tracy':60}
d['Uzi'] = 100
d['Bob']
d[1] = 99
a = 2
d[a] = 98
d

{1: 99, 2: 98, 'Bob': 75, 'Mike': 94, 'Tracy': 60, 'Uzi': 100}

如果key不存在，dict就会报错。可以通过`in`判断key是否存在；或者通过dict提供的`get()`方法，如果key不存在可以返回`None`，或者自己指定的value

In [4]:
d = {'Mike':94, 'Bob':75, 'Tracy':60}
d['Uzi'] = 100

if 'Uzi' in d:
    print(d['Uzi'])
else:
    print('not here')

p = d.get('smlz', 1)

if p != 1:
    print(d['smlz'])
else:
    print('not here')

#### set
* set与dict类似，也是一组key的集合，但不存储value。  
* 要创建set，需要提供一个list作为输入集合  
* 通过`add(key)`和`remove(key)`添加删除元素
* set与dict的唯一区别在于没有存储对应的value

In [6]:
s = set([1, 2, 3])
print(s)
s.add('mike')
print(s)
s.remove(1)
print(s)

{1, 2, 3}
{'mike', 1, 2, 3}
{'mike', 2, 3}


### 函数
**函数名是指向一个函数对象的引用，完全可以把函数名赋给一个变量，相当于给这个函数起了一个别名**

In [13]:
a = abs
print(a(-1))

1


In [16]:
n1 = 255
n2 = 1000
print(hex(n1), hex(n2), sep ='\n')

0xff
0x3e8


#### `def` 函数，定义函数
```
def function_name(parameters):
    expressions
```
* 使用`def`语句，依次写出函数名，括号，参数，冒号。在缩进块中编写函数体，函数的返回值用`return`语句返回。**(不需要定义返回值？)**  
* 注意：函数体内部的语句在执行时，遇到`return`时函数执行完毕。

In [18]:
def my_abs(a):
    if a < 0:
        return -a
    else:
        return a
print(my_abs(-3))

3


#### 空函数
* 定义一个什么都不做的空函数
```
def nop():
    pass
```
* `pass`语句可以作为占位符.
* `pass`还可以用在其他语句里.  

#### 参数检查
* 调用参数时如果参数个数不对,Python解释器会自动检查出来,并抛出`Type Error`
* 如果参数类型不对,Python解释器无法帮我们检查.
* 因此需要我们完善函数定义
* 数据类型检查可以用内置函数`isinstance()`实现:

In [26]:
def my_abs(x):
    if not isinstance(x, (int, float)):
        raise TypeError('bad operand type')
    if  x >= 0:
        return x
    else:
        return -x
# print(my_abs('abc'))
print(my_abs(-1))

1


#### 返回多个值
* Python函数返回的是一个tuple,但是在语法上,返回一个tuple可以省略括号
* 多个变量可以同时接受一个tuple,按位置赋给对应的值.

In [30]:
import math
def move(x, y, step, angle = 0):
    nx = x + step * math.cos(angle)
    ny = y - step * math.sin(angle)
    return nx, ny

x, y = move(100, 100, 60, math.pi / 6)
r = move(100, 100, 60, math.pi / 6)
print('x = %.10f, y = %.2f' %(r[0],r[1]))


x = 151.9615242271, y = 70.00


In [37]:
# 练习
import math
def quadratic(a, b, c):
    delta = b ** 2 - 4 * a * c
    if delta > 0:
        x1 = (-b + math.sqrt(delta))/( 2 * a)
        x2 = (-b - math.sqrt(delta))/( 2 * a)
        return x1, x2
    elif delta == 0:
        x = b / (2 * a)
        return x
    else:
        print('no result!')
x = quadratic(2, 3, 1)
print(x)
y = quadratic(1, 3, -4)
print(y)

# 测试:
print('quadratic(2, 3, 1) =', quadratic(2, 3, 1))
print('quadratic(1, 3, -4) =', quadratic(1, 3, -4))

if quadratic(2, 3, 1) != (-0.5, -1.0):
    print('测试失败')
elif quadratic(1, 3, -4) != (1.0, -4.0):
    print('测试失败')
else:
    print('测试成功')

(-0.5, -1.0)
(1.0, -4.0)
quadratic(2, 3, 1) = (-0.5, -1.0)
quadratic(1, 3, -4) = (1.0, -4.0)
测试成功


#### 函数的参数
* 必选参数
* 默认参数
* 可变参数
* 关键字参数

##### 位置参数
* 调用函数时,传入的值按照位置顺序依次付给参数
* 如果忘记了函数参数的位置，只知道参数的名字，可以在函数调用过程中给指明的参数

In [104]:
def testfunction2(a, b):
    print('This is testfunction2!')
    c = (a + 1) * b
    print('c = a + b = %d' %c)
testfunction2(b = 2, a = 1)

This is testfunction2!
c = a + b = 4


##### 默认参数
* 简化函数的调用
* 必选参数在前,默认参数在后
* 通常将变化小的参数用作默认参数
* 按照顺序提供默认参数,如果不按照默认顺序需要写上参数名
* **注意默认参数必须指向不变对象**:常量,字符串,tuple(应该可以吧)

如果改变了默认参数的数据类型会怎样?会报错!!

In [8]:
def add_end(L = [1, 2]):
    L.append('end')
    return L

print(add_end([1]))  # 没有使用默认参数
print(add_end())
print(add_end())

[1, 'end']
[1, 2, 'end']
[1, 2, 'end', 'end']


可以看到上面的例子中,默认参数`L`是一个列表,是可变对象(注意与变量区分),在每次调用该函数时,会改变该对象,也就是改变了默认参数,因此一定要令默认参数为不可变对象

In [ ]:
def add_end_new(L = None):
    if L is None:
        L = []
    L.append('end')
    return L



#### 可变参数
* 传入的参数的个数是可变的
* 作为一个tuple传入的
* 在定义时不能出现在特定参数和默认参数前面

In [9]:
# numbers 是一个tuple
def calc(numbers):
    sum = 0
    for n in numbers:
        sum = sum + n
    return sum
c = (1, 2, 3)  # 需要定义一个tuple(或者list)
print(calc(c))

# numbers 为可变参数
def calc_new(*numbers):
    sum = 0
    for n in numbers:
        sum = sum + n
    return sum
print(calc_new(1,2,3)) #直接传入参数

# 也可以直接将tuple或者list加*传入
print(calc_new(*c))

6
6
6


可变参数与其他类型参数一起用

In [26]:
def test1(a, b = 2, *numbers):
    sum = 0
    print(b)
    print(numbers)
test1(1)
test1(1, 2, 3)
test1(1, 3, 4, 5)
test1(1,(1, 2))  # 默认参数b = 2, 但是这里认为是(1, 2)中的1

2
()
2
(3,)
3
(4, 5)
(1, 2)
()


#### 关键字参数
* 关键字参数传入0个或者任意个含参数名的参数,在函数内部自动组装为一个dict.
* 用于扩展函数功能
* 也可以先组装出一个字典,然后用`**`把该字典转换为关键字参数传入

In [121]:
def portrait(name, **kw):
    print('name is', name)
    for k,v in kw.items():
        print(k, v) # 那是不是说，k为参数名，w为参数值？     
portrait('lixiang', age = 27, country = 'china')

name is lixiang
age 27
country china


In [ ]:
def person(name, age, **kw)

In [ ]:
def testfunction(a):
    print('This is a testfunction')
    b = a + 1
    print('b = %d' % b)
    
testfunction(5)
    

#### 命名关键字参数
* 限制关键字参数的名字
* 通过`*`隔开其他类型的参数
* 如果函数定义中有一个可变参数,那么后面的命名关键字参数不再需要`*`分隔
* 命名关键字参数**必须**传入参数名(与位置参数不同)
* 命名关键字参数可以有缺省值,从而简化调用(为什么不用默认参数?)

In [30]:
def person(name, age, *, city = 'Beijing', job):
    print(name, age, city, job)
    
person('Jack Ma', 60, city = 'Hangzhou', job = 'ceo')
person('Tony Ma', 70, job = 'ceo')
person('Jone Snow',20, city = 'Winterfall', job = 'killer')


Jack Ma 60 Hangzhou ceo
Tony Ma 70 Beijing ceo
Jone Snow 20 Winterfall killer


#### 参数组合
* Python中定义函数,可以用必选参数,默认参数,可变参数,关键字参数,和命名关键字参数,都可以组合使用
* 参数定义的顺序必须是:必选参数,默认参数,可变参数,**命名关键字参数**,关键字参数
* 如果定义了默认参数,同时还定义了可变参数,那么在调用函数时不能省略默认参数
* 对于任意函数,都可以通过类似`func(*args, **kw)`的形式调用,无论它的参数是如何定义的

In [54]:
def f1(a, b, c = 0, *args, **kw):  #分别定义了必选参数a,b;默认参数c = 0;可变参数args;关键字参数kw
    print('a =', a, 'b =', b, 'c =', c, 'args =', args, 'kw =', kw)
f1(1, 2)
f1(1, 2, c = 3)
f1(1, 2, 3, 'a', 'b')
f1(1, 2, 3, 4, 'b')
f1(1, 2, job = 'CEO')

args = (1, 2, 3, 4, 5)
kw = {'d': 99, 'x':'#'}
f1(2,*args, **kw)  #args的元素按顺序自动传给了未赋值的参数,剩下的成为了可变参数的一部分(前提是函数必须定义了可变参数).

a = 1 b = 2 c = 0 args = () kw = {}
a = 1 b = 2 c = 3 args = () kw = {}
a = 1 b = 2 c = 3 args = ('a', 'b') kw = {}
a = 1 b = 2 c = 3 args = (4, 'b') kw = {}
a = 1 b = 2 c = 0 args = () kw = {'job': 'CEO'}
a = 2 b = 1 c = 2 args = (3, 4, 5) kw = {'d': 99, 'x': '#'}


In [53]:
def f2(a, b, c = 0, *, d, **kw):  #定义了命名关键字参数d
    print('a =', a, 'b =', b, 'c =', c, 'd =', d, 'kw =', kw)
f2(1, 2, d = 3)
f2(1, 2, 3, d = 4, e = 5)
arg = (1, 2, 3)
f2(*arg, d = 4, e = 5)

a = 1 b = 2 c = 0 d = 3 kw = {}
a = 1 b = 2 c = 3 d = 4 kw = {'e': 5}
a = 1 b = 2 c = 3 d = 4 kw = {'e': 5}


#### 练习:

In [66]:
def product(x, *y):
    if x is None:
        raise TypeError('bad')
    else:
        result  = x
        for i in y:
            result = result * i
        return result

# 测试
print('product(5) =', product(5))
print('product(5, 6) =', product(5, 6))
print('product(5, 6, 7) =', product(5, 6, 7))
print('product(5, 6, 7, 9) =', product(5, 6, 7, 9))
if product(5) != 5:
    print('测试失败!')
elif product(5, 6) != 30:
    print('测试失败!')
elif product(5, 6, 7) != 210:
    print('测试失败!')
elif product(5, 6, 7, 9) != 1890:
    print('测试失败!')
else:
    try:
        product()
        print('测试失败!')
    except TypeError:
        print('测试成功!')    

        
        

product(5) = 5
product(5, 6) = 30
product(5, 6, 7) = 210
product(5, 6, 7, 9) = 1890
测试成功!


**自调用**，在执行脚本时执行一些代码，比如单元测试，可以在脚本最后加上单元测试代码，但是该脚本作为一个模块对外提供功能的时候测试代码也会执行，这些往往是不想要的，可以将这些代码加入脚本最后：
```
if _name_== '_main_':
    #code_here
```
这段代码具体是怎么实现的？跟自调用有什么关系？